apiVersion: v1
kind: Service
metadata:
  name: rest
  labels:
    app: rest
    role: api
    run: rest-api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5080
  selector:
    app: rest
    run: rest-api
  type: NodePort